# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Topping',
        ),
    ]
